### ISSUE TITLE
html2warc  not getting the style or css for replayweb page app

### ISSUE THREAD

**Issue by hamoudak** [netzliteratur/html2warc#1]
I have followed your instructions on usage with an offline directory . when I play the warc file with replay webpage there's just html files and images , it didn't get the resources such as css folder , js  or any thing of this . when I click on any html file in the app I get a message :

Archived Page Not Found
Sorry, this page was not found in this archive:

https://solar.lowtechmagazine.com/E:/Bookshelf/Low-tech-folder/Solar_lowtechmagazine/2008/02/a-world-without-trucks-underground-freight-networks/images/dithers/reseau-de-tubes-pneumtiques-paris_dithered.png

[Click Here](https://solar.lowtechmagazine.com/E:/Bookshelf/Low-tech-folder/Solar_lowtechmagazine/2008/02/a-world-without-trucks-underground-freight-networks/images/dithers/reseau-de-tubes-pneumtiques-paris_dithered.png) to try to load the live page in a new tab (or to download the URL as a file).

am on windows machine (10)

I ran the command : python html2warc.py https://solar.lowtechmagazine.com/  E:\Bookshelf\Low-tech-folder\Solar_lowtechmagazine-en  C:\html2warc\solar_lowtech
 I got no issues in the command window.

here are some screen shots to clarify my issue and I hope to find out what to do about it.
<img width="960" alt="replaywebpage-html_urls" src="https://github.com/netzliteratur/html2warc/assets/155604457/2af8c96e-25f6-4b09-9704-5e775ec68eb2">

<img width="960" alt="all_urls_not_working" src="https://github.com/netzliteratur/html2warc/assets/155604457/97ead45b-9e67-41b9-bc61-51f3ad4a5501">

<img width="960" alt="offline_directoy_of_website" src="https://github.com/netzliteratur/html2warc/assets/155604457/10cf4973-bc60-4d7b-817b-07835356e318">
<img width="960" alt="html2warc-folder_warc_inside" src="https://github.com/netzliteratur/html2warc/assets/155604457/7059b784-845a-4a37-869a-12dfb58371d9">

**Comment by dla-kramski** [comment]
Sorry, this repo is inactive. 

Please see https://github.com/steffenfritz/html2warc instead.

Regards,
   Heinz

**Comment by hamoudak** [comment]
hey , I have used the other project not this one, but I don't see ( issues section) there, so I came here to see an answer for this problem or anyone can help me how to do this right .

**Comment by netzliteratur** [comment]
Simply be the first at https://github.com/steffenfritz/html2warc/issues.

Regards, Heinz
